version: '3.8'
services:
  dev-db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456!
      POSTGRES_DB: taskanager
    networks:
      - freecodecamp
networks:
  freecodecamp:
